// Repeatable browser acceptance suite. Supply a Playwright installation and an isolated Chrome CDP URL.
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const {chromium}=await import(process.env.TORO_PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.connectOverCDP(process.env.TORO_BROWSER_CDP);
const context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true,offline:process.env.TORO_QA_OFFLINE==='1'});
const page=await context.newPage();page.setDefaultTimeout(12000);
const url=process.env.TORO_QA_URL||'http://localhost:5174';
const output=path.resolve(process.env.TORO_QA_OUT||'.sites-runtime/single-tests/browser');await fs.mkdir(output,{recursive:true});
const require=createRequire(path.resolve('.sites-runtime/room-tests/package.json'));
const {catalog}=require('./room.js'),{createTemplate}=require('./toro-templates.js'),{parseSingle}=require('./workspace.js');
const networkRequests=[];page.on('request',request=>{if(/^https?:/.test(request.url()))networkRequests.push(request.url());});
const errors=[],consoleProblems=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',msg=>{if(['error','warning'].includes(msg.type()))consoleProblems.push(msg.text());});
let stage='start';const results=[];
const report=name=>{results.push(name);console.log('PASS '+name);};
async function stored(){await page.getByRole('button',{name:'Návrh',exact:true}).click();await page.getByRole('menuitem',{name:'Uložit návrh',exact:true}).click();return page.evaluate(()=>JSON.parse(localStorage.getItem('toro-workspace-v1')));}
async function number(label,value){const input=page.getByRole('spinbutton',{name:label,exact:true});await input.fill(String(value));await input.press('Enter');}
async function download(button,name){const pending=page.waitForEvent('download');await button.click();const file=await pending;const dest=path.join(output,name);await file.saveAs(dest);return JSON.parse(await fs.readFile(dest,'utf8'));}
async function upload(value,name='fixture.json'){const filename=path.join(output,name);await fs.writeFile(filename,JSON.stringify(value));await page.locator('input[type=file][accept=".json,application/json"]').first().setInputFiles(filename);}
async function noOverflow(){assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'Horizontal page overflow');}
try{
  stage='initial';await page.goto(url);await page.getByRole('heading',{name:'Šatní skříň',level:1}).waitFor();await page.locator('canvas').waitFor();await page.waitForFunction(()=>document.querySelector('canvas')?.width>0);assert.equal((await stored()).room,null);assert.equal(await page.getByText('Umístění v pokoji',{exact:true}).count(),0);await noOverflow();await page.screenshot({path:path.join(output,'01-single-desktop.png'),fullPage:true});report('Clean default, true standalone controls and rendered canvas');
  stage='single export';await number('Šířka',180);await number('Výška',240);let state=await stored();assert.equal(state.single.width,180);const concept=structuredClone(state.single);await page.getByRole('button',{name:'Návrh',exact:true}).click();let file=await download(page.getByRole('menuitem',{name:'Stáhnout kus',exact:true}),'single-design.json');assert.deepEqual(parseSingle(file),concept);await number('Šířka',190);await page.locator('input[type=file][accept=".json,application/json"]').first().setInputFiles(path.join(output,'single-design.json'));assert.deepEqual((await stored()).single,concept);report('Real single-design download and file import');
  stage='single inquiry';await page.getByRole('button',{name:'Přehled a poptávka',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByRole('img',{name:'Aktuální pohled na váš návrh'}).waitFor();await page.waitForFunction(()=>document.querySelector('.toro-summary-preview img')?.src.startsWith('data:image/png'));assert.equal(await dialog.getByText('Rozměry místnosti, dveře a okna',{exact:true}).count(),0);await dialog.getByRole('button',{name:'Připravit poptávku',exact:true}).click();await dialog.getByRole('button',{name:'Doplnit ukázkové údaje'}).click();file=await download(dialog.getByRole('button',{name:'Stáhnout podklady poptávky'}),'single-inquiry.json');assert.deepEqual(parseSingle(file),concept);assert(!('room' in file.design));assert(file.preview.startsWith('data:image/png'));assert(!('plan' in file.previews));await dialog.getByRole('button',{name:'Zpět k návrhu'}).click();await page.locator('input[type=file][accept=".json,application/json"]').first().setInputFiles(path.join(output,'single-inquiry.json'));assert.deepEqual((await stored()).single,concept);report('Real roomless inquiry with PNG, example contact and re-import');
  stage='new room';await page.getByRole('button',{name:'Vložit do pokoje',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Zpět ke kusu'}).click();assert.equal((await stored()).room,null);await page.getByRole('button',{name:'Vložit do pokoje',exact:true}).click();await page.getByRole('button',{name:'Vytvořit a vložit kus'}).click();await page.getByRole('region',{name:'Pracovní plocha pokoje'}).waitFor();state=await stored();assert.equal(state.room.items.length,1);assert.equal(state.room.items[0].width,180);const itemId=state.room.items[0].id;report('Cancelled creation retains concept; confirmed creation inserts it');
  stage='edit cancel';await page.getByRole('button',{name:'Vlastnosti vybraného prvku'}).click();await number('Šířka',230);await page.getByRole('button',{name:'Zrušit úpravy',exact:true}).click();state=await stored();assert.equal(state.room.items[0].width,180);assert.deepEqual(state.single,concept);
  stage='edit commit reload';await page.getByRole('button',{name:'Vlastnosti vybraného prvku'}).click();await number('Šířka',240);await stored();await page.reload();await page.getByRole('button',{name:'Použít změny v pokoji'}).waitFor();assert.equal((await stored()).edit.draft.width,240);await page.getByRole('button',{name:'Použít změny v pokoji'}).click();state=await stored();assert.equal(state.room.items[0].id,itemId);assert.equal(state.room.items[0].width,240);assert.equal(state.room.items.length,1);assert.deepEqual(state.single,concept);report('Edit cancellation, page restoration and identity-preserving commit');
  stage='switch repeated insert';await page.getByRole('button',{name:'Jeden kus nábytku',exact:true}).click();assert.equal(await page.getByRole('spinbutton',{name:'Šířka',exact:true}).inputValue(),'180');await page.getByRole('button',{name:'Vložit do pokoje',exact:true}).click();state=await stored();assert.equal(state.room.items.length,2);assert.notEqual(state.room.items[0].id,state.room.items[1].id);await page.getByRole('button',{name:'Vrátit poslední změnu'}).click();assert.equal((await stored()).room.items.length,1);await page.getByRole('button',{name:'Znovu provést změnu'}).click();assert.equal((await stored()).room.items.length,2);report('Mode preservation, repeated insertion and undo/redo');
  stage='all catalogue types';await page.getByRole('button',{name:'Jeden kus nábytku',exact:true}).click();
  for(const [index,entry] of catalog.entries()){
    await page.getByRole('button',{name:'Vybrat typ nábytku'}).click();await page.getByRole('dialog').getByRole('button',{name:new RegExp('^'+entry.name)}).click();assert.equal((await stored()).single.type,entry.type);await page.locator('canvas').waitFor();await noOverflow();
    assert.equal(await page.getByText('Umístění v pokoji',{exact:true}).count(),0);
    const steps=await page.getByRole('navigation',{name:'Kroky návrhu'}).getByRole('button').all();for(const step of steps)await step.click();await page.getByRole('navigation',{name:'Kroky návrhu'}).getByRole('button',{name:'Rozměry',exact:true}).click();
    if(['bed','vanity','custom','builtin'].includes(entry.type))await page.screenshot({path:path.join(output,`type-${entry.type}.png`),fullPage:true});
    if(index===catalog.length-1){await page.getByRole('textbox',{name:'Zadání atypického kusu'}).fill('Ukázkový atyp s otvorem; detail se upřesní s TORO.');assert((await stored()).single.notes.includes('Ukázkový atyp'));}
  }
  report('All fifteen types, actual controls, geometry and custom brief');
  stage='bathroom preservation';const bath=createTemplate('bath');await upload(bath,'bath.json');state=await stored();assert.equal(state.room.technicalPoints.length,bath.technicalPoints.length);const savedBath=structuredClone(state.room);await page.getByRole('button',{name:'Jeden kus nábytku',exact:true}).click();await page.getByRole('button',{name:'Vybrat typ nábytku'}).click();await page.getByRole('dialog').getByRole('button',{name:/^Nástěnná police/}).click();await page.getByRole('button',{name:'Vložit do pokoje',exact:true}).click();state=await stored();assert.equal(state.room.items.length,bath.items.length+1);assert.deepEqual(state.room.technicalPoints,savedBath.technicalPoints);assert.deepEqual(state.room.room,savedBath.room);report('Insertion into existing bathroom preserves all openings and technical links');
  stage='room inquiry';await page.getByRole('navigation',{name:'Postup návrhu'}).getByRole('button',{name:/Poptávka/}).click();await page.getByRole('complementary',{name:'Poptávka'}).getByRole('button',{name:'Připravit poptávku'}).click();dialog=page.getByRole('dialog');await page.waitForFunction(()=>document.querySelector('.tw-inquiry-views figure:nth-child(2) img')?.src.startsWith('data:image/png'));assert.equal(await dialog.locator('.tw-inquiry-views img').count(),2);await page.screenshot({path:path.join(output,'room-inquiry.png'),fullPage:true});await dialog.getByRole('button',{name:'Připravit poptávku',exact:true}).click();await dialog.getByRole('button',{name:'Doplnit ukázkové údaje'}).click();file=await download(dialog.getByRole('button',{name:'Stáhnout podklady poptávky'}),'room-inquiry.json');assert.equal(file.design.items.length,bath.items.length+1);assert(file.previews.perspective.startsWith('data:image/png'));assert(file.previews.plan.startsWith('data:image/svg+xml'));assert.deepEqual(file.design.technicalPoints,bath.technicalPoints);await dialog.getByRole('button',{name:'Zpět k návrhu'}).click();await page.locator('input[type=file][accept=".json,application/json"]').first().setInputFiles(path.join(output,'room-inquiry.json'));assert.deepEqual((await stored()).room,file.design);report('Real room inquiry download with both previews, utilities and file re-import');
  stage='room geometry';await page.getByRole('navigation',{name:'Postup návrhu'}).getByRole('button',{name:/Prostor/}).click();await page.getByRole('navigation',{name:'Vlastnosti pokoje'}).getByRole('button',{name:'Dveře a okna',exact:true}).click();await page.getByRole('button',{name:'Okno',exact:true}).click();state=await stored();assert.equal(state.room.room.openings.length,bath.room.openings.length+1);await page.getByRole('button',{name:'Vrátit poslední změnu'}).click();assert.equal((await stored()).room.room.openings.length,bath.room.openings.length);await upload(createTemplate('bedroom'),'bedroom.json');state=await stored();assert(state.room.room.outline.length>4);assert(state.room.room.openings.filter(o=>o.type==='window').length>=2);await page.getByRole('button',{name:'2D',exact:true}).click();await page.screenshot({path:path.join(output,'room-plan.png'),fullPage:true});report('Room openings, history and imported L plan with multiple windows');
  stage='mobile';for(const width of [320,390,768]){
    await page.setViewportSize({width,height:900});await page.waitForTimeout(200);if(await page.getByRole('button',{name:'Zavřít panel',exact:true}).isVisible())await page.getByRole('button',{name:'Zavřít panel',exact:true}).click();await page.getByRole('button',{name:'Jeden kus nábytku',exact:true}).click();await noOverflow();await page.screenshot({path:path.join(output,`mobile-single-${width}.png`),fullPage:true});
    await page.getByRole('button',{name:'Přehled a poptávka',exact:true}).click();dialog=page.getByRole('dialog');await noOverflow();await dialog.getByRole('button',{name:'Připravit poptávku',exact:true}).click();await noOverflow();await page.screenshot({path:path.join(output,`mobile-contact-${width}.png`),fullPage:true});await page.keyboard.press('Escape');
    await page.getByRole('button',{name:'Celý pokoj',exact:true}).click();await noOverflow();await page.screenshot({path:path.join(output,`mobile-room-${width}.png`),fullPage:true});
  }report('Responsive single, room and contact layouts at 320, 390 and 768 pixels');
  await page.setViewportSize({width:1440,height:1050});
  stage='legacy and errors';const legacy={width:240,height:280,depth:80,material:'walnut',front:'graphite',sections:['hanging','drawers','shelves'],doors:'hinged',handles:'brass'};
  await upload(legacy,'legacy-wardrobe.json');state=await stored();for(const key of Object.keys(legacy))assert.deepEqual(state.single[key],legacy[key]);const before=structuredClone(state);await upload({format:'toro-furniture',version:99,item:{}},'invalid.json');assert.deepEqual(await stored(),before);report('Legacy wardrobe file migration and invalid-import preservation');
  stage='corrupt storage';const corrupt=await context.newPage();await corrupt.goto(url);await corrupt.getByRole('button',{name:'Návrh',exact:true}).waitFor();await corrupt.evaluate(()=>localStorage.setItem('toro-workspace-v1','{broken'));await corrupt.reload();await corrupt.getByRole('alert').waitFor();await corrupt.waitForTimeout(650);assert.equal(await corrupt.evaluate(()=>localStorage.getItem('toro-workspace-v1')),'{broken');await corrupt.getByRole('button',{name:'Obnovit ukládání'}).click();assert(await corrupt.evaluate(()=>Object.keys(localStorage).some(k=>k.startsWith('toro-workspace-v1-backup-')&&localStorage.getItem(k)==='{broken')));await corrupt.close();report('Damaged local data blocks automatic overwrite and recovers with backup');
  stage='fallback';const fallback=await browser.newContext({viewport:{width:390,height:900},offline:process.env.TORO_QA_OFFLINE==='1'});await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(kind,...args){return String(kind).includes('webgl')?null:original.call(this,kind,...args);};});const fallbackPage=await fallback.newPage();await fallbackPage.goto(url);await fallbackPage.getByText('3D náhled není k dispozici',{exact:true}).waitFor();await fallbackPage.getByRole('button',{name:'Přehled a poptávka',exact:true}).click();assert(await fallbackPage.getByRole('dialog').getByRole('img').count()>0);await fallbackPage.screenshot({path:path.join(output,'fallback-inquiry.png'),fullPage:true});await fallback.close();report('Unavailable WebGL keeps configuration and schematic inquiry usable');
  assert.equal(errors.length,0,errors.join('\n'));report('No uncaught browser errors in the normal acceptance journey');
  if(process.env.TORO_QA_OFFLINE==='1'){assert.equal(networkRequests.length,0,networkRequests.join('\n'));report('File URL with network disabled made zero HTTP requests');}
  await fs.writeFile(path.join(output,'results.json'),JSON.stringify({url,results,errors,consoleProblems,networkRequests},null,2));
}catch(error){await page.screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{});await fs.writeFile(path.join(output,'failure.txt'),`${stage}\n${error.stack}\n${await page.locator('body').innerText()}`);throw Error(`${stage}: ${error.message}`,{cause:error});}
finally{await context.close();await browser.close();}
