'use client';
import { useState } from 'react';
import { ArrowLeft, Check, ChevronRight, CircleAlert, Download, PlugZap, Plus, Trash2 } from 'lucide-react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { NativeSelect } from './ui/native-select';
import { FurnitureIcon, NumberField } from './room-controls';
import { catalog, wallNames, type FurnitureType, type Issue, type RoomDesign, type TechnicalPoint, type Wall } from '@/lib/room';
import { furnitureCategories } from '@/lib/toro-templates';

export function FurnitureCatalog({design,onAdd,onSelect,onTemplates}:{design:RoomDesign;onAdd:(type:FurnitureType)=>void;onSelect:(id:string)=>void;onTemplates:()=>void}) {
  const [category,setCategory]=useState('all');
  const entries=catalog.filter(c=>category==='all'||(furnitureCategories.find(g=>g.id===category)?.types as readonly string[])?.includes(c.type));
  return <div className="tw-panel-content"><span className="tw-eyebrow">NÁBYTEK</span><h2>Co do pokoje patří?</h2><label className="toro-field-label">Kategorie<NativeSelect value={category} onChange={e=>setCategory(e.target.value)}>{furnitureCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</NativeSelect></label><div className="tw-catalog">{entries.map(c=><button key={c.type} onClick={()=>onAdd(c.type)} aria-label={`Přidat ${c.name}`}><FurnitureIcon type={c.type} size={27}/><strong>{c.name}</strong><Plus size={15}/></button>)}</div><Button variant="outline" onClick={onTemplates}>Vybrat připravenou sestavu</Button><h3>V pokoji · {design.items.length}</h3><div className="tw-item-list">{design.items.map(item=><button key={item.id} onClick={()=>onSelect(item.id)}><FurnitureIcon type={item.type}/><span><strong>{item.name}</strong><small>{item.width} × {item.height} × {item.depth} cm</small></span><ChevronRight size={17}/></button>)}{!design.items.length&&<p>Vyberte první kus z nabídky.</p>}</div></div>;
}

export function TechnicalPanel({design,selected,onChange,onDelete,onSelect,onPlace,onAddDefault,placing,onCancel}:{design:RoomDesign;selected:TechnicalPoint|undefined;onChange:(patch:Partial<TechnicalPoint>)=>void;onDelete:()=>void;onSelect:(id:string|null)=>void;onPlace:()=>void;onAddDefault:()=>void;placing:boolean;onCancel:()=>void}) {
  if(selected) {
    const wallLength=selected.wall==='north'||selected.wall==='south'?design.room.width:design.room.length;
    return <div className="tw-panel-content"><Button variant="ghost" onClick={()=>onSelect(null)}><ArrowLeft/> Všechny technické prvky</Button><span className="tw-eyebrow">ELEKTŘINA</span><h2>Zásuvka 230 V</h2><label className="toro-field-label">Název<Input value={selected.name} maxLength={80} onChange={e=>onChange({name:e.target.value||'Zásuvka 230 V'})}/></label><label className="toro-field-label">Stěna<NativeSelect value={selected.wall} onChange={e=>onChange({wall:e.target.value as Wall})}>{Object.entries(wallNames).map(([wall,name])=><option key={wall} value={wall}>{name}</option>)}</NativeSelect></label><NumberField label={selected.wall==='north'||selected.wall==='south'?'Od levého rohu ke středu':'Od zadního rohu ke středu'} value={selected.offset} min={selected.width/2} max={wallLength-selected.width/2} onChange={offset=>onChange({offset})}/><NumberField label="Výška středu nad podlahou" value={selected.elevation} min={selected.height/2} max={design.room.height-selected.height/2} onChange={elevation=>onChange({elevation})}/><p className="tw-note">Polohu měřte ke středu zásuvky. Zkontrolujeme, zda k ní nábytek neomezuje přístup.</p><details className="tw-details"><summary>Rozměry rámečku</summary><NumberField label="Šířka rámečku" value={selected.width} min={6} max={30} onChange={width=>onChange({width})}/><NumberField label="Výška rámečku" value={selected.height} min={6} max={30} onChange={height=>onChange({height})}/></details><Button variant="outline" onClick={onDelete}><Trash2/> Odebrat zásuvku</Button></div>;
  }
  return <div className="tw-panel-content"><span className="tw-eyebrow">TECHNICKÉ PRVKY / ELEKTŘINA</span><h2>Přípojná místa</h2><p>Zaznamenejte zásuvky, ke kterým potřebujete přístup.</p>{placing?<div className="tw-placement"><strong>Klikněte ke stěně v půdorysu.</strong><p>Přesnou vzdálenost a výšku pak upravíte.</p><Button variant="outline" onClick={onCancel}>Zrušit umístění</Button></div>:<Button className="tw-primary" disabled={(design.technicalPoints?.length??0)>=100} onClick={onPlace}><PlugZap/> Umístit zásuvku</Button>}<Button variant="ghost" disabled={(design.technicalPoints?.length??0)>=100} onClick={onAddDefault}>Přidat zadáním rozměrů</Button><h3>V návrhu · {design.technicalPoints?.length??0}</h3><div className="tw-item-list">{(design.technicalPoints??[]).map((point,index)=><button key={point.id} onClick={()=>onSelect(point.id)}><PlugZap/><span><strong>Z{index+1} · {point.name}</strong><small>{wallNames[point.wall]} · výška {point.elevation} cm</small></span><ChevronRight size={17}/></button>)}</div></div>;
}

export function CheckPanel({issues,onSelect}:{issues:Issue[];onSelect:(issue:Issue)=>void}) {
  const severity={info:'Informace',warning:'Upozornění',problem:'Problém'};
  return <div className="tw-panel-content"><span className="tw-eyebrow">KONTROLA NÁVRHU</span><h2>{issues.length?'Místa k dořešení':'Bez zjevných kolizí'}</h2>{!issues.length&&<div className="tw-check-clear"><Check size={28}/><p>Nábytek, otvory a zásuvky si podle zadaných rozměrů nepřekážejí.</p></div>}<div className="tw-issues">{issues.map(issue=><button key={issue.id} className={`tw-issue tw-${issue.severity}`} onClick={()=>onSelect(issue)}><CircleAlert size={20}/><span><strong>{severity[issue.severity]}</strong>{issue.text}<small>Zobrazit místo v návrhu</small></span></button>)}</div><p className="tw-note">Kontrola je orientační. U zásuvek sleduje překrytí nábytkem a krátký prostor před rámečkem. Skutečný přístup a montáž ověříte s TORO.</p></div>;
}

export function InquiryPanel({design,issues,onOpen,onService,onExport,onCheck}:{design:RoomDesign;issues:Issue[];onOpen:()=>void;onService:()=>void;onExport:()=>void;onCheck:()=>void}) {
  return <div className="tw-panel-content"><span className="tw-eyebrow">POPTÁVKA</span><h2>Váš návrh pro TORO</h2><p>Projděte souhrn, doplňte kontakt a fotografie a stáhněte podklady.</p><dl className="tw-summary"><div><dt>Pokoj</dt><dd>{design.room.width} × {design.room.length} cm</dd></div><div><dt>Nábytek k výrobě</dt><dd>{design.items.filter(i=>!i.existing).length} ks</dd></div><div><dt>Technické prvky</dt><dd>{design.technicalPoints?.length??0}</dd></div></dl>{issues.length>0&&<Button variant="outline" onClick={onCheck}><CircleAlert/> Projít upozornění ({issues.length})</Button>}<Button className="tw-primary" onClick={onOpen}>Připravit poptávku <ChevronRight/></Button><Button variant="outline" onClick={onExport}><Download/> Stáhnout upravitelný návrh</Button><Button variant="ghost" onClick={onService}>Montáž nebo atypická zakázka</Button><p className="tw-note">Podklady se uloží do souboru. Odeslání přímo do TORO zatím není připojeno.</p></div>;
}
