'use client';
import { useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Download, FileCheck2, ImagePlus, X } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { NativeSelect } from '@/components/ui/native-select';
import { Switch } from '@/components/ui/switch';
import { materials } from '@/lib/configuration';
import { describeDesign, downloadText } from '@/lib/toro-inquiry';
import { issuesFor, type RoomDesign } from '@/lib/room';
import { FurnitureIcon } from './room-controls';

type Photo={name:string;data:string};
export function InquiryDialog({open,onOpenChange,design,preview,service=false,standalone=false}:{open:boolean;onOpenChange:(v:boolean)=>void;design:RoomDesign;preview:string;service?:boolean;standalone?:boolean}){
  const [step,setStep]=useState(0),[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[city,setCity]=useState('');
  const [notes,setNotes]=useState(''),[assembly,setAssembly]=useState(true),[timing,setTiming]=useState('Dle domluvy'),[kind,setKind]=useState('Montáž nábytku');
  const [photos,setPhotos]=useState<Photo[]>([]),[error,setError]=useState(''),[loadingPhotos,setLoadingPhotos]=useState(false);
  const designSummary=(standalone?'Samostatná skříň. Pokoj v exportu slouží pouze pro zobrazení; nejde o zaměřenou místnost.\n\n':'')+describeDesign(design);
  const offered=design.items.filter(i=>!i.existing),issues=issuesFor(design),existingCount=design.items.filter(i=>i.existing).length;
  async function loadPhotos(files:FileList|null){
    if(!files)return;setError('');
    const next=[...files];if(next.length+photos.length>3){setError('Přidejte nejvýše 3 fotografie.');return;}
    if(next.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>2_000_000)){setError('Použijte JPG, PNG nebo WebP, každý do 2 MB.');return;}
    setLoadingPhotos(true);
    try{const loaded=await Promise.all(next.map(f=>new Promise<Photo>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:f.name,data:String(reader.result)});reader.onerror=()=>reject(Error('Fotografii se nepodařilo načíst.'));reader.readAsDataURL(f);})));setPhotos(p=>[...p,...loaded]);}catch{setError('Fotografie se nepodařilo načíst. Zkuste je přidat znovu.');}finally{setLoadingPhotos(false);}
  }
  function download(){
    const payload={format:'toro-inquiry',version:1,createdAt:new Date().toISOString(),kind:service?kind:'Nábytek na míru',contact:{name,email,phone,city},assembly,timing,notes,photos,design:service?null:design,preview:service?null:preview,summary:service?notes:designSummary,warnings:service?[]:issues.map(i=>i.text)};
    downloadText(JSON.stringify(payload,null,2),'TORO-poptavka.json','application/json');setStep(2);
  }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="toro-dialog toro-inquiry-dialog"><DialogHeader><span className="toro-eyebrow">TORO INTERIORS / {service?'MONTÁŽ A ATYPICKÉ ZAKÁZKY':'VÁŠ NÁVRH'}</span><DialogTitle>{step===2?'Podklady jsou připravené.':step===1?'Pár detailů pro truhláře.':service?'S čím vám můžeme pomoci?':'Takhle může vypadat váš domov.'}</DialogTitle><DialogDescription>{step===2?'Soubor můžete předat truhláři a společně návrh doladit.':step===1?'Doplňte kontakt a představu o realizaci.':service?'Přiložte fotografii, rozměry nebo popis práce.':'Zkontrolujte sestavu a připravte zadání pro individuální nabídku.'}</DialogDescription></DialogHeader>
    {step<2&&<div className="toro-request-steps"><span className={step===0?'active':''}>01 {service?'Zadání':'Sestava'}</span><i/><span className={step===1?'active':''}>02 Kontakt a realizace</span></div>}
    {step===0&&!service&&<><div className="toro-summary-grid">{preview&&<div className="toro-summary-preview"><img src={preview} alt="Aktuální pohled na váš návrh"/><span>{standalone?'Samostatná skříň':`${design.room.width} × ${design.room.length} cm · ${design.title||'Můj pokoj'}`}</span></div>}<div className="toro-summary-items">{offered.length===0?<p>V návrhu není žádný kus určený k výrobě.</p>:offered.map(i=><div key={i.id}><FurnitureIcon type={i.type}/><span><strong>{i.name}</strong><small>{i.width} × {i.height} × {i.depth} cm</small><small>{i.construction==='solid'?'Masiv':'Lamino'} · {materials.find(m=>m.id===i.material)?.name}</small></span><Check size={16}/></div>)}</div></div>{design.items.some(i=>i.existing)&&<p className="toro-info-note">Stávající nábytek ({existingCount}) zůstává pouze v prostorovém návrhu.</p>}{issues.length>0&&<div className="toro-warnings"><strong>K návrhu je potřeba dořešit</strong>{issues.map(i=><p key={i.id}>{i.text}</p>)}</div>}<div className="toro-quote-note"><FileCheck2 size={24}/><div><strong>Cenovou nabídku připraví TORO.</strong><p>Podle finálního zaměření, materiálu, kování a montáže.</p></div></div><div className="toro-dialog-actions"><Button variant="outline" onClick={()=>downloadText('\uFEFF'+designSummary,'TORO-soupis.txt')}><Download size={16}/> Stáhnout soupis</Button><Button disabled={!offered.length} onClick={()=>setStep(1)}>Připravit poptávku <ArrowRight size={16}/></Button></div></>}
    {step===0&&service&&<><label className="toro-field-label">Typ zakázky<NativeSelect value={kind} onChange={e=>setKind(e.target.value)}>{['Montáž nábytku','Kuchyňská linka','Schodiště a obklad','Dveře a parapety','Atypický nábytek','Kompletní interiér'].map(k=><option key={k}>{k}</option>)}</NativeSelect></label><label className="toro-field-label">Co potřebujete vyřešit?<Textarea value={notes} maxLength={4000} onChange={e=>setNotes(e.target.value)} placeholder="Například: montáž kuchyně do L, délky 280 a 180 cm. Nábytek už máme objednaný…" rows={5}/></label><div className="toro-dialog-actions"><Button disabled={!notes.trim()} onClick={()=>setStep(1)}>Pokračovat <ArrowRight size={16}/></Button></div></>}
    {step===1&&<form className="toro-contact-form" onSubmit={e=>{e.preventDefault();download();}}><div className="toro-form-grid"><label className="toro-field-label">Jméno<Input autoComplete="name" value={name} onChange={e=>setName(e.target.value)} maxLength={100} placeholder="Vaše jméno" required/></label><label className="toro-field-label">E-mail<Input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} maxLength={150} placeholder="vas@email.cz" required/></label><label className="toro-field-label">Telefon <span>nepovinné</span><Input type="tel" autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)} maxLength={40} placeholder="+420"/></label><label className="toro-field-label">Město realizace<Input autoComplete="address-level2" value={city} onChange={e=>setCity(e.target.value)} maxLength={120} placeholder="Např. Plzeň" required/></label></div><div className="toro-form-grid"><label className="toro-field-label">Představa o termínu<NativeSelect value={timing} onChange={e=>setTiming(e.target.value)}>{['Dle domluvy','Do 3 měsíců','Za 3–6 měsíců','Zatím sbírám inspiraci'].map(t=><option key={t}>{t}</option>)}</NativeSelect></label><label className="toro-existing"><Switch checked={assembly} onCheckedChange={setAssembly}/><span>Mám zájem o montáž<small>Upřesníme podle místa realizace.</small></span></label></div>{!service&&<label className="toro-field-label">Poznámka k návrhu<Textarea rows={3} value={notes} maxLength={4000} onChange={e=>setNotes(e.target.value)} placeholder="Co je pro vás důležité?"/></label>}<div className="toro-photo-field"><label className="toro-photo-upload"><ImagePlus size={20}/><span>{loadingPhotos?'Načítám fotografie…':'Přidat fotografie místnosti'}<small>JPG, PNG, WebP · až 3 fotografie, každá do 2 MB</small></span><Input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={loadingPhotos} onChange={e=>{void loadPhotos(e.target.files);e.target.value='';}} aria-label="Přidat fotografie místnosti"/></label>{photos.length>0&&<div className="toro-photo-list">{photos.map((p,i)=><div key={`${p.name}-${i}`}><img src={p.data} alt={p.name}/><button type="button" aria-label={`Odebrat ${p.name}`} onClick={()=>setPhotos(a=>a.filter((_,n)=>n!==i))}><X size={14}/></button></div>)}</div>}{error&&<p role="alert" className="toro-form-error">{error}</p>}</div><p className="toro-prototype-note">Ukázka poptávky: údaje a fotografie se uloží pouze do staženého souboru. Nic se neodesílá.</p><div className="toro-dialog-actions"><Button type="button" variant="outline" onClick={()=>setStep(0)}><ArrowLeft size={16}/> Zpět</Button><Button type="submit" disabled={loadingPhotos}><Download size={16}/> Stáhnout podklady poptávky</Button></div></form>}
    {step===2&&<div className="toro-request-done"><span><Check size={32}/></span><h3>Vše v jednom souboru</h3><p>Zadání{!service?', upravitelný pokoj a jeho náhled':''}, kontakt i přiložené fotografie jsou ve staženém souboru <strong>TORO-poptavka.json</strong>.</p><p>Poptávka zatím nebyla odeslána. Tento prototyp připravuje podklady k předání.</p><Button onClick={()=>onOpenChange(false)}>Zpět k návrhu</Button><Button variant="ghost" onClick={download}><Download size={16}/> Stáhnout znovu</Button></div>}
    </DialogContent></Dialog>;
}
