'use client';
import { useState } from 'react';
import { ArrowRight, Box, Check, House, Plus, Wrench } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { templates, createTemplate, type TemplateId } from '@/lib/toro-templates';
import { catalog, type FurnitureType } from '@/lib/room';
import { FurnitureIcon } from './room-controls';

export function TemplateIllustration({id}:{id:TemplateId}){
  const d=createTemplate(id),scale=.65;
  if(id==='bedroom')return <svg viewBox="0 0 320 170" role="img" aria-label="Náhled: Ložnice do L"><path d="M55 10H265V92H181V160H55Z" fill="#e2d9ca" stroke="#6d6254" strokeWidth="3"/><path d="M69 10h46m59 0h42" stroke="#93b9c1" strokeWidth="5"/><rect x="83" y="17" width="64" height="67" rx="2" fill="#f6f1e8" stroke="#a67d54" strokeWidth="3"/><rect x="88" y="22" width="24" height="15" rx="3" fill="white"/><rect x="118" y="22" width="24" height="15" rx="3" fill="white"/><path d="M84 44h62" stroke="#ba9469"/><rect x="224" y="16" width="35" height="27" fill="#d5c6b3" stroke="#6d6254"/><path d="M241 16v27" stroke="#6d6254"/><rect x="63" y="122" width="28" height="21" fill="#ba9469" stroke="#6d6254"/><path d="M143 160h30" stroke="#f8f6f1" strokeWidth="4"/></svg>;
  return <svg viewBox="0 0 320 170" role="img" aria-label={`Náhled: ${d.title}`}><defs><pattern id={`wood-${id}`} width="8" height="16" patternUnits="userSpaceOnUse"><rect width="8" height="16" fill="#ba9469"/><path d="M2 0v16M7 2v10" stroke="#a67d54" strokeWidth=".5" opacity=".6"/></pattern></defs><path d="M15 145h290l-34 20H40z" fill="#e2d9ca"/><path d="M15 145V12h290v133" fill="#f0ede7" stroke="#e2dbcf"/>{d.items.map(i=>{const x=160+(i.x-i.width/2)*scale,y=145-(i.y+i.height)*.47,w=i.width*scale,h=i.height*.47;return <g key={i.id} stroke="#6d6254" strokeWidth=".8"><rect x={x} y={y} width={w} height={h} fill={i.type==='mirror'?'#c1d2d4':i.front==='white'?'#fffdfa':i.type==='builtin'||i.type==='shoe'?'#d5c6b3':`url(#wood-${id})`}/>{['builtin','dresser','shoe','tv','laundry'].includes(i.type)?<>{Array.from({length:Math.max(2,i.sections.length)-1},(_,k)=><path key={k} d={`M${x+w*(k+1)/Math.max(2,i.sections.length)} ${y}v${h}`} />)}</>:i.type==='bench'||i.type==='desk'?<rect x={x+4} y={y+3} width={w-8} height={h-5} fill="#f0ede7"/>:i.type==='bookcase'?Array.from({length:4},(_,k)=><path key={k} d={`M${x} ${y+h*(k+1)/5}h${w}`}/>):i.type==='panel'?Array.from({length:i.hooks||4},(_,k)=><path key={k} d={`M${x+w*(k+1)/((i.hooks||4)+1)} ${y+h*.3}v8`} stroke="#292724" strokeWidth="2"/>):null}{i.type==='vanity'&&Array.from({length:i.basins||1},(_,k)=><ellipse key={k} cx={x+w*(k+.5)/(i.basins||1)} cy={y+3} rx={w/(i.basins||1)*.27} ry={5} fill="white"/>)}{i.type==='laundry'&&[0,1].map(k=><circle key={k} cx={x+w/2} cy={y+h*.4+k*h*.35} r={w*.25} fill="#bac5c7"/>)}</g>})}</svg>;
}

export function ProjectChooser({open,onOpenChange,onTemplate,onEmpty,onSingle,onService}:{open:boolean;onOpenChange:(open:boolean)=>void;onTemplate:(id:TemplateId)=>void;onEmpty:()=>void;onSingle:(type:FurnitureType)=>void;onService:()=>void}){
  const [mode,setMode]=useState<'room'|'single'>('room');
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="toro-dialog toro-project-dialog"><DialogHeader><span className="toro-eyebrow">NOVÝ NÁVRH / TORO INTERIORS</span><DialogTitle>Čím začneme?</DialogTitle><DialogDescription>Vyberte si základ. Rozměry, materiály i jednotlivé kusy pak doladíte po svém.</DialogDescription></DialogHeader><div className="toro-project-modes"><button className={mode==='room'?'active':''} aria-pressed={mode==='room'} onClick={()=>setMode('room')}><House size={20}/><span>Celá sestava<small>Vybavte si místnost</small></span>{mode==='room'&&<Check size={16}/>}</button><button className={mode==='single'?'active':''} aria-pressed={mode==='single'} onClick={()=>setMode('single')}><Box size={20}/><span>Jeden kus<small>Začněte konkrétním nábytkem</small></span>{mode==='single'&&<Check size={16}/>}</button><button onClick={onService}><Wrench size={20}/><span>Montáž / atyp<small>Popište nám svou představu</small></span><ArrowRight size={16}/></button></div>{mode==='room'?<div className="toro-template-grid">{templates.map(t=><button key={t.id} className="toro-template-card" onClick={()=>onTemplate(t.id)}><TemplateIllustration id={t.id}/><div><span>{t.tag}</span><h3>{t.name}</h3><p>{t.detail}</p><span className="toro-template-cta">Upravit tuto sestavu <ArrowRight size={16}/></span></div></button>)}<button className="toro-template-card toro-empty-template" onClick={onEmpty}><Plus size={34}/><h3>Prázdný pokoj</h3><p>Začněte vlastním nápadem.</p></button></div>:<div className="toro-single-grid">{catalog.map(c=><button key={c.type} onClick={()=>onSingle(c.type)}><FurnitureIcon type={c.type} size={30}/><strong>{c.name}</strong><span>{c.description}</span><ArrowRight size={15}/></button>)}</div>}<p className="toro-dialog-footnote">Výběr nahradí aktuální pokoj. Předchozí návrh můžete vrátit tlačítkem Zpět.</p></DialogContent></Dialog>;
}

export function TemplateRibbon({onChoose,onService}:{onChoose:()=>void;onService:()=>void}){
  return <div className="toro-start-strip"><div className="toro-start-icon"><House size={21}/></div><div><strong>Váš nápad. Náš řemeslný základ.</strong><span>Začněte hotovou sestavou, jedním kusem nebo prázdným pokojem.</span></div><Button variant="outline" onClick={onChoose}>Vybrat jiný základ <ArrowRight size={15}/></Button><button className="toro-service-link" onClick={onService}><Wrench size={15}/> Montáž / atyp</button></div>;
}
